# Generated by Django 3.2.16 on 2025-04-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipe_amounts', through='recipes.IngredientAmount', to='recipes.Ingredient'),
        ),
    ]
