# Generated by Django 3.2.16 on 2025-04-20 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20250418_0208'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientAmount',
            new_name='RecipeIngredients',
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_favorite',
        ),
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='unique_name_measurement_unit',
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='unique_shopping_cart',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='measurement_unit',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='name',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='user',
        ),
    ]
